"""Add disabled field to agents

Revision ID: e924b7161259
Revises: 
Create Date: 2025-10-27 23:13:42.365306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e924b7161259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('disabled', sa.Boolean(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_port_reservations_id'), 'port_reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_port_reservations_id'), table_name='port_reservations')
    op.drop_column('agents', 'disabled')
    # ### end Alembic commands ###
